{{- if .Values.awsSecretsManager.enabled }}
# ============================================
# SERVICE ACCOUNT (IRSA - IAM Roles for Service Accounts)
# ============================================
# Utilisé par les pods pour accéder à AWS Secrets Manager
# L'annotation eks.amazonaws.com/role-arn associe ce SA à un IAM Role AWS
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: devops-microservices
    app.kubernetes.io/managed-by: helm
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.awsSecretsManager.iamRoleArn | quote }}
{{- end }}
