{{- if .Values.services.reviewService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.reviewService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.services.reviewService.name }}
    {{- if .Values.monitoring.enabled }}
    monitoring: "true"
    {{- end }}
  {{- if eq .Values.ingress.className "alb" }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/reviews/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.reviewService.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.services.reviewService.name }}
{{- end }}
